-- ============================================================
-- CareerFit — Migration v15: Ngân hàng câu hỏi phỏng vấn THEO NGÀNH
-- 17 nhóm ngành × (chuyên môn + tình huống thực tế + hành vi) + câu chung.
-- worker.py chọn câu theo ngành đã nhận diện, kỹ năng khớp/thiếu và bằng
-- chứng trong CV (thay cho bộ câu hỏi chung chung trước đây).
-- File này sinh tự động bởi packages/ml-service/scripts/gen_interview_bank_sql.py
-- Copy toàn bộ file này vào Supabase > SQL Editor > Run (chạy lại nhiều lần an toàn)
-- ============================================================

-- Rubric chấm điểm cho từng câu (trang phỏng vấn giả lập so khớp từ khoá)
alter table public.interview_questions add column if not exists expected  text[] not null default '{}';
alter table public.interview_questions add column if not exists red_flags text[] not null default '{}';

-- Chống trùng khi chạy lại
create unique index if not exists idx_interview_questions_unique
  on public.interview_questions (coalesce(industry_id, '00000000-0000-0000-0000-000000000000'::uuid), md5(question));


-- kinh-doanh-ban-hang
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), 'Quản lý pipeline bán hàng', 'technical', 'mid',
   'Bạn quản lý pipeline bán hàng của mình như thế nào? Hãy nêu các giai đoạn, chỉ số bạn theo dõi ở từng giai đoạn và cách bạn xử lý khi tỷ lệ chuyển đổi giữa hai giai đoạn bị giảm.',
   ARRAY['Nêu rõ các giai đoạn: tiếp cận, tìm hiểu nhu cầu, báo giá, đàm phán, chốt hợp đồng', 'Theo dõi chỉ số: tỷ lệ chuyển đổi, giá trị đơn hàng, thời gian chốt', 'Phân tích nguyên nhân tụt tỷ lệ chuyển đổi và có hành động khắc phục cụ thể']::text[],
   ARRAY['Bán hàng theo cảm tính, không có quy trình', 'Không đo lường bất kỳ số liệu nào']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), 'Đàm phán giá', 'technical', 'mid',
   'Khách hàng nói giá bên bạn cao hơn đối thủ 15%. Bạn đàm phán thế nào để vẫn chốt được mà giữ được biên lợi nhuận?',
   ARRAY['Tìm hiểu tiêu chí thật sự của khách, so sánh giá trị thay vì chỉ so giá', 'Nhấn mạnh lợi ích khác biệt: chất lượng, bảo hành, dịch vụ hậu mãi', 'Nhượng bộ có điều kiện (số lượng, hình thức thanh toán, thời hạn hợp đồng) thay vì giảm giá thẳng']::text[],
   ARRAY['Giảm giá ngay để chốt', 'Nói xấu đối thủ']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), 'Dự báo doanh số', 'technical', 'senior',
   'Bạn lập dự báo doanh số tháng hoặc quý dựa trên những dữ liệu nào? Làm sao để dự báo sát với thực tế?',
   ARRAY['Dựa trên pipeline hiện tại, tỷ lệ chốt lịch sử và yếu tố mùa vụ', 'Chia dự báo theo khách hàng, khu vực hoặc sản phẩm', 'So sánh dự báo với thực tế định kỳ và điều chỉnh']::text[],
   ARRAY['Dự báo theo cảm tính', 'Không theo dõi sai lệch giữa dự báo và thực tế']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), null, 'situational', 'mid',
   'Một khách hàng lớn đột nhiên ngừng đặt hàng hai tháng liên tiếp và không trả lời điện thoại. Bạn sẽ làm gì?',
   ARRAY['Liên hệ qua nhiều kênh: email, gặp trực tiếp, người liên hệ khác trong công ty khách', 'Kiểm tra vấn đề phía mình: chất lượng, giao hàng, giá, đối thủ chen vào', 'Đề xuất giải pháp giữ chân khách và kế hoạch theo dõi cụ thể']::text[],
   ARRAY['Chờ khách tự liên hệ lại', 'Đổ lỗi cho khách hàng']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), null, 'situational', 'mid',
   'Còn một tuần là hết quý nhưng bạn mới đạt 70% chỉ tiêu doanh số. Bạn xử lý thế nào?',
   ARRAY['Rà soát pipeline để tìm các cơ hội sắp chốt', 'Ưu tiên khách hàng tiềm năng cao, đẩy nhanh quyết định mua', 'Báo cáo trung thực với quản lý và rút kinh nghiệm cho quý sau']::text[],
   ARRAY['Hứa hẹn sai sự thật hoặc ép khách để chốt', 'Buông xuôi, không có hành động']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), null, 'situational', 'junior',
   'Bạn phát hiện một đồng nghiệp đang chăm sóc và báo giá cho khách hàng mà bạn đã theo từ trước. Bạn xử lý thế nào?',
   ARRAY['Trao đổi trực tiếp, bình tĩnh với đồng nghiệp', 'Dựa trên dữ liệu lịch sử chăm sóc trên CRM', 'Nhờ quản lý phân xử theo quy định, ưu tiên trải nghiệm của khách hàng']::text[],
   ARRAY['Tranh cãi trước mặt khách', 'Tự ý hạ giá để giành lại khách']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), null, 'behavioral', 'mid',
   'Hãy kể về thương vụ khó nhất bạn từng chốt được: khó ở điểm nào và bạn đã làm gì khác biệt?',
   ARRAY['Mô tả bối cảnh và khó khăn cụ thể của thương vụ', 'Nêu rõ hành động của chính bạn', 'Kết quả: giá trị hợp đồng và bài học rút ra']::text[],
   ARRAY['Không có ví dụ cụ thể', 'Kết quả chỉ nhờ may mắn']::text[]),
  ((select id from public.industries where slug = 'kinh-doanh-ban-hang'), null, 'behavioral', 'junior',
   'Bạn làm thế nào để giữ động lực khi bị khách hàng từ chối liên tục nhiều ngày?',
   ARRAY['Xem lời từ chối là dữ liệu để cải thiện cách tiếp cận', 'Đặt mục tiêu nhỏ hằng ngày, có thói quen làm việc đều đặn', 'Học hỏi từ đồng nghiệp và quản lý']::text[],
   ARRAY['Dễ nản, đổ lỗi cho sản phẩm', 'Không có cách tự điều chỉnh']::text[])
on conflict do nothing;

-- marketing-truyen-thong
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'marketing-truyen-thong'), 'Digital Advertising', 'technical', 'mid',
   'Chiến dịch quảng cáo Facebook hoặc Google của bạn có chi phí mỗi chuyển đổi (CPA) tăng gấp đôi sau một tuần. Bạn phân tích và tối ưu như thế nào?',
   ARRAY['Phân tích theo phễu: CTR, CPC, tỷ lệ chuyển đổi của landing page', 'Kiểm tra tệp đối tượng, tần suất hiển thị, creative bị bão hoà', 'Test A/B creative và tệp mới, phân bổ lại ngân sách theo hiệu quả (ROAS)']::text[],
   ARRAY['Tăng ngân sách mà không phân tích', 'Không nắm các chỉ số CTR, CPA, ROAS']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), 'Content Strategy', 'technical', 'mid',
   'Bạn xây dựng kế hoạch nội dung một tháng cho fanpage của thương hiệu như thế nào? Đo hiệu quả bằng những chỉ số gì?',
   ARRAY['Xác định mục tiêu và chân dung khách hàng mục tiêu', 'Chia tuyến nội dung, lịch đăng và định dạng (video, bài viết, livestream)', 'Chỉ số đo: reach, engagement, CTR, chuyển đổi']::text[],
   ARRAY['Đăng bài theo cảm hứng', 'Chỉ quan tâm lượt like']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), 'Branding', 'technical', 'senior',
   'Theo bạn, định vị thương hiệu gồm những yếu tố nào? Hãy phân tích một thương hiệu Việt Nam định vị tốt.',
   ARRAY['Khách hàng mục tiêu, lợi ích khác biệt, lý do để tin tưởng', 'Nhất quán thông điệp và hình ảnh ở mọi điểm chạm', 'Có ví dụ thương hiệu cụ thể và phân tích được']::text[],
   ARRAY['Nhầm branding với thiết kế logo', 'Không đưa được ví dụ']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), null, 'situational', 'mid',
   'Một bài đăng của thương hiệu bị cộng đồng mạng phản ứng tiêu cực và lan truyền rất nhanh. Bạn xử lý 24 giờ đầu như thế nào?',
   ARRAY['Theo dõi, đánh giá mức độ khủng hoảng', 'Phản hồi nhanh, chân thành, thống nhất thông điệp với cấp trên', 'Đính chính hoặc gỡ nội dung, rút kinh nghiệm quy trình duyệt bài']::text[],
   ARRAY['Xoá bình luận tiêu cực và im lặng', 'Tranh cãi với người dùng']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), null, 'situational', 'senior',
   'Ngân sách marketing quý bị cắt 40% nhưng mục tiêu doanh số vẫn giữ nguyên. Bạn ưu tiên như thế nào?',
   ARRAY['Phân tích hiệu quả từng kênh theo ROI hoặc CPA', 'Cắt kênh kém hiệu quả, dồn ngân sách vào kênh tốt nhất', 'Tận dụng kênh không tốn phí: SEO, cộng đồng, khách hàng cũ']::text[],
   ARRAY['Cắt đều tất cả các kênh', 'Quyết định không dựa trên số liệu']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), null, 'situational', 'mid',
   'Sếp muốn thuê một KOL nổi tiếng, nhưng tệp người theo dõi của KOL không trùng khách hàng mục tiêu. Bạn góp ý thế nào?',
   ARRAY['Phân tích tệp follower và tỷ lệ tương tác thật của KOL', 'Đề xuất phương án micro-KOL hoặc KOC phù hợp hơn', 'Đưa số liệu dự kiến chi phí và hiệu quả để thuyết phục']::text[],
   ARRAY['Làm theo mà không góp ý', 'Phản đối nhưng không có dữ liệu']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), null, 'behavioral', 'mid',
   'Hãy kể về chiến dịch bạn tự hào nhất: mục tiêu là gì, bạn làm những gì và kết quả bằng số liệu ra sao?',
   ARRAY['Nêu mục tiêu chiến dịch rõ ràng', 'Mô tả vai trò và hành động của bạn', 'Kết quả có số liệu: reach, chuyển đổi, doanh thu']::text[],
   ARRAY['Không có số liệu kết quả', 'Kể chung chung thành tích của cả team']::text[]),
  ((select id from public.industries where slug = 'marketing-truyen-thong'), null, 'behavioral', 'mid',
   'Kể về một chiến dịch không đạt kỳ vọng. Nguyên nhân là gì và bạn rút ra bài học gì?',
   ARRAY['Thừa nhận thẳng thắn kết quả không đạt', 'Phân tích được nguyên nhân gốc', 'Bài học đã áp dụng cho chiến dịch sau']::text[],
   ARRAY['Đổ lỗi hoàn toàn cho người khác', 'Không rút ra bài học']::text[])
on conflict do nothing;

-- cntt
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'cntt'), 'SQL', 'technical', 'mid',
   'Một câu truy vấn SQL dùng cho báo cáo chạy mất 30 giây. Bạn tìm nguyên nhân và tối ưu như thế nào?',
   ARRAY['Dùng EXPLAIN để xem execution plan', 'Thêm index phù hợp, tránh SELECT *, tránh dùng hàm trên cột được lọc', 'Giảm join không cần thiết, phân trang, cache hoặc bảng tổng hợp']::text[],
   ARRAY['Chỉ đề xuất nâng cấp server', 'Không biết execution plan và index']::text[]),
  ((select id from public.industries where slug = 'cntt'), 'API', 'technical', 'mid',
   'Bạn thiết kế REST API cho chức năng đặt hàng như thế nào? Hãy nêu các endpoint, mã trạng thái HTTP và cách xử lý lỗi.',
   ARRAY['Endpoint theo tài nguyên, dùng đúng method GET, POST, PUT, DELETE', 'Mã trạng thái hợp lý: 200, 201, 400, 401, 404, 500', 'Validate dữ liệu, xác thực, idempotency, versioning']::text[],
   ARRAY['Dùng GET cho mọi thao tác', 'Không validate hay xử lý lỗi']::text[]),
  ((select id from public.industries where slug = 'cntt'), 'Git', 'technical', 'junior',
   'Hai người cùng sửa một file và bị conflict khi merge. Bạn xử lý thế nào, và team bạn dùng quy trình branch ra sao?',
   ARRAY['Pull hoặc rebase, đọc hiểu phần conflict, trao đổi với người cùng sửa', 'Chạy lại test sau khi resolve conflict', 'Quy trình: feature branch, pull request, code review']::text[],
   ARRAY['Ghi đè code của người khác', 'Push thẳng lên nhánh main']::text[]),
  ((select id from public.industries where slug = 'cntt'), 'ReactJS', 'technical', 'mid',
   'Trong React, khi nào một component bị render lại? Bạn đã tối ưu một màn hình bị chậm như thế nào?',
   ARRAY['State hoặc props thay đổi, component cha render lại', 'Dùng memo, useMemo, useCallback, đặt key đúng cho danh sách', 'Đo bằng React DevTools Profiler, chia nhỏ component, lazy load']::text[],
   ARRAY['Không biết nguyên nhân re-render', 'Tối ưu mà không đo lường']::text[]),
  ((select id from public.industries where slug = 'cntt'), 'Docker', 'technical', 'mid',
   'Docker giải quyết vấn đề gì? Bạn đóng gói và triển khai một ứng dụng bằng Docker như thế nào?',
   ARRAY['Đồng nhất môi trường chạy, cô lập ứng dụng', 'Viết Dockerfile, build image, chạy container, dùng docker-compose', 'Quản lý biến môi trường, volume, tích hợp CI/CD']::text[],
   ARRAY['Nhầm Docker với máy ảo', 'Chưa từng viết Dockerfile']::text[]),
  ((select id from public.industries where slug = 'cntt'), null, 'situational', 'mid',
   'Sau khi deploy phiên bản mới, hệ thống production chậm hẳn và người dùng phản ánh liên tục. Bạn xử lý thế nào?',
   ARRAY['Đánh giá mức độ ảnh hưởng, rollback nếu cần', 'Xem log và monitoring: CPU, RAM, truy vấn chậm, lỗi', 'Tìm nguyên nhân gốc, viết postmortem, bổ sung test và giám sát']::text[],
   ARRAY['Sửa nóng trên production không kiểm soát', 'Không có kế hoạch rollback']::text[]),
  ((select id from public.industries where slug = 'cntt'), null, 'situational', 'mid',
   'Deadline còn 3 ngày nhưng khách hàng yêu cầu thêm một tính năng mới. Bạn làm gì?',
   ARRAY['Đánh giá khối lượng công việc, rủi ro và ảnh hưởng tiến độ', 'Trao đổi với PM và khách hàng: ưu tiên, cắt phạm vi hoặc lùi deadline', 'Thống nhất bằng văn bản, không hy sinh kiểm thử và chất lượng']::text[],
   ARRAY['Nhận hết rồi làm thâu đêm, bỏ qua test', 'Từ chối mà không giải thích']::text[]),
  ((select id from public.industries where slug = 'cntt'), null, 'situational', 'senior',
   'Khi review code, bạn thấy đồng nghiệp senior viết đoạn code có lỗ hổng SQL injection. Bạn góp ý thế nào?',
   ARRAY['Góp ý thẳng thắn, lịch sự, có bằng chứng cụ thể', 'Đề xuất cách sửa: parameterized query hoặc ORM', 'Đề xuất bổ sung checklist review hoặc công cụ quét bảo mật']::text[],
   ARRAY['Bỏ qua vì ngại người có kinh nghiệm hơn', 'Chê bai công khai']::text[]),
  ((select id from public.industries where slug = 'cntt'), null, 'behavioral', 'mid',
   'Hãy kể về bug khó nhất bạn từng xử lý: bạn đã tìm ra nguyên nhân bằng cách nào?',
   ARRAY['Mô tả hiện tượng lỗi và mức độ ảnh hưởng', 'Các bước khoanh vùng: log, debug, tái hiện lỗi', 'Nguyên nhân gốc và cách phòng tránh tái diễn']::text[],
   ARRAY['Không nhớ ví dụ cụ thể', 'Sửa được nhưng không hiểu vì sao']::text[]),
  ((select id from public.industries where slug = 'cntt'), null, 'behavioral', 'junior',
   'Bạn tự học một công nghệ mới như thế nào? Công nghệ gần nhất bạn học là gì và đã áp dụng vào đâu?',
   ARRAY['Có phương pháp: tài liệu chính thức, làm dự án nhỏ, đọc mã nguồn', 'Nêu công nghệ cụ thể vừa học', 'Đã áp dụng vào dự án thực tế']::text[],
   ARRAY['Chỉ xem video, không thực hành', 'Không kể được công nghệ nào']::text[])
on conflict do nothing;

-- ke-toan-tai-chinh
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), 'Lập báo cáo tài chính', 'technical', 'mid',
   'Bộ báo cáo tài chính của doanh nghiệp gồm những báo cáo nào? Bạn kiểm tra tính khớp đúng giữa các báo cáo ra sao?',
   ARRAY['Bảng cân đối kế toán, báo cáo kết quả kinh doanh, lưu chuyển tiền tệ, thuyết minh', 'Đối chiếu lợi nhuận chưa phân phối, số dư tiền cuối kỳ giữa các báo cáo', 'Kiểm tra với sổ cái và sổ chi tiết']::text[],
   ARRAY['Không kể đủ các báo cáo', 'Không biết cách đối chiếu chéo']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), 'Kế toán thuế', 'technical', 'mid',
   'Cuối tháng bạn làm những việc gì liên quan đến thuế GTGT? Nếu hoá đơn đầu vào sai thông tin thì xử lý thế nào?',
   ARRAY['Tập hợp, kiểm tra hoá đơn đầu vào và đầu ra, lập tờ khai', 'Kê khai và nộp thuế đúng hạn', 'Hoá đơn sai: liên hệ bên bán lập biên bản, xuất hoá đơn điều chỉnh hoặc thay thế']::text[],
   ARRAY['Vẫn kê khai hoá đơn sai thông tin', 'Không nắm hạn nộp tờ khai']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), 'Excel', 'technical', 'junior',
   'Bạn dùng Excel để đối chiếu 5.000 dòng công nợ giữa sổ sách và sao kê ngân hàng như thế nào?',
   ARRAY['Dùng VLOOKUP hoặc XLOOKUP, SUMIFS, Pivot Table', 'Chuẩn hoá dữ liệu trước khi đối chiếu', 'Lọc các dòng chênh lệch và tìm nguyên nhân']::text[],
   ARRAY['Dò thủ công từng dòng', 'Không biết hàm tra cứu']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), null, 'situational', 'junior',
   'Cuối kỳ, số dư tiền mặt trên sổ lệch 12 triệu so với thực tế kiểm quỹ. Bạn xử lý thế nào?',
   ARRAY['Kiểm tra lại chứng từ thu chi và việc ghi sổ', 'Đối chiếu với thủ quỹ, lập biên bản kiểm kê quỹ', 'Báo cáo cấp trên và xử lý chênh lệch theo quy định']::text[],
   ARRAY['Tự điều chỉnh số liệu cho khớp', 'Không báo cáo']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), null, 'situational', 'mid',
   'Sếp yêu cầu bạn đưa một khoản chi không có chứng từ hợp lệ vào chi phí để giảm thuế. Bạn làm gì?',
   ARRAY['Giải thích rủi ro: bị loại chi phí, truy thu và phạt khi quyết toán', 'Đề xuất phương án hợp lệ: bổ sung chứng từ', 'Giữ nguyên tắc nghề nghiệp']::text[],
   ARRAY['Làm theo yêu cầu sai', 'Im lặng, không cảnh báo rủi ro']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), null, 'situational', 'senior',
   'Đơn vị kiểm toán phát hiện một sai sót trong phần số liệu bạn phụ trách. Bạn phản hồi thế nào?',
   ARRAY['Tiếp nhận, kiểm tra lại và xác nhận sai sót', 'Điều chỉnh bút toán và giải trình với kiểm toán', 'Cải thiện quy trình kiểm soát để tránh lặp lại']::text[],
   ARRAY['Chối bỏ trách nhiệm', 'Che giấu sai sót']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), null, 'behavioral', 'mid',
   'Kể về lần bạn phát hiện ra một sai sót quan trọng trong số liệu kế toán. Bạn đã phát hiện và xử lý thế nào?',
   ARRAY['Mô tả sai sót và mức ảnh hưởng', 'Cách bạn phát hiện: đối chiếu, kiểm tra chéo', 'Hành động khắc phục và bài học']::text[],
   ARRAY['Không có ví dụ', 'Không nêu được cách kiểm soát']::text[]),
  ((select id from public.industries where slug = 'ke-toan-tai-chinh'), null, 'behavioral', 'junior',
   'Mùa quyết toán có rất nhiều việc gấp cùng lúc. Bạn sắp xếp công việc như thế nào để không sai sót?',
   ARRAY['Lập danh sách công việc và hạn chót', 'Ưu tiên theo mức độ quan trọng và thời hạn pháp lý', 'Kiểm tra lại trước khi nộp']::text[],
   ARRAY['Làm theo cảm hứng', 'Chấp nhận sai sót vì vội']::text[])
on conflict do nothing;

-- nhan-su-hanh-chinh
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), 'Tuyển dụng', 'technical', 'mid',
   'Bạn cần tuyển 10 nhân viên kinh doanh trong một tháng. Kế hoạch tuyển dụng của bạn như thế nào?',
   ARRAY['Xác định tiêu chí và mô tả công việc cùng bộ phận', 'Chọn kênh: website việc làm, mạng xã hội, giới thiệu nội bộ, trường học', 'Quy trình sàng lọc, phỏng vấn và chỉ số theo dõi: số CV, tỷ lệ đạt, thời gian tuyển']::text[],
   ARRAY['Chỉ đăng tin rồi chờ', 'Không có tiêu chí đánh giá ứng viên']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), 'Tính lương', 'technical', 'mid',
   'Bảng lương tháng của nhân viên gồm những khoản nào? Bạn tính các khoản bảo hiểm bắt buộc và thuế TNCN ra sao?',
   ARRAY['Lương cơ bản, phụ cấp, thưởng, làm thêm giờ', 'Trích BHXH, BHYT, BHTN theo tỷ lệ quy định', 'Thuế TNCN: giảm trừ gia cảnh và biểu thuế lũy tiến']::text[],
   ARRAY['Không nắm tỷ lệ trích bảo hiểm', 'Không biết giảm trừ gia cảnh']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), 'Luật lao động', 'technical', 'senior',
   'Một nhân viên nghỉ việc ngang không báo trước. Công ty xử lý theo Bộ luật Lao động như thế nào?',
   ARRAY['Thời hạn báo trước theo loại hợp đồng lao động', 'Nghĩa vụ bồi thường khi đơn phương chấm dứt hợp đồng trái luật', 'Chốt sổ BHXH, thanh toán các khoản trong thời hạn quy định']::text[],
   ARRAY['Giữ lương hoặc giấy tờ trái luật', 'Không nắm quy định pháp luật']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), null, 'situational', 'mid',
   'Hai trưởng phòng mâu thuẫn gay gắt và cùng đến phàn nàn với bạn. Bạn xử lý thế nào?',
   ARRAY['Lắng nghe riêng từng bên, giữ khách quan', 'Tìm hiểu nguyên nhân gốc của mâu thuẫn', 'Tổ chức trao đổi chung, thống nhất giải pháp và theo dõi']::text[],
   ARRAY['Đứng về một phía', 'Lờ đi để tự giải quyết']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), null, 'situational', 'mid',
   'Một nhân viên giỏi xin nghỉ vì lương thấp hơn thị trường. Bạn làm gì?',
   ARRAY['Trao đổi để hiểu lý do thật sự', 'Tham khảo dữ liệu lương thị trường, đề xuất với ban lãnh đạo', 'Xem xét lộ trình phát triển và chính sách giữ chân nhân tài']::text[],
   ARRAY['Để nhân viên nghỉ mà không tìm hiểu', 'Hứa hẹn tăng lương khi chưa được duyệt']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), null, 'situational', 'senior',
   'Một nhân viên phản ánh bị quấy rối tại nơi làm việc. Bạn xử lý như thế nào?',
   ARRAY['Tiếp nhận nghiêm túc, bảo mật thông tin người phản ánh', 'Điều tra khách quan theo quy trình, thu thập bằng chứng', 'Xử lý kỷ luật theo nội quy và pháp luật, bảo vệ người phản ánh']::text[],
   ARRAY['Xem nhẹ hoặc bỏ qua phản ánh', 'Tiết lộ danh tính người phản ánh']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), null, 'behavioral', 'mid',
   'Kể về một chính sách hoặc quy trình nhân sự bạn đã đề xuất và triển khai. Kết quả thế nào?',
   ARRAY['Vấn đề cần giải quyết', 'Cách bạn thiết kế và triển khai', 'Kết quả đo được']::text[],
   ARRAY['Không có ví dụ cụ thể', 'Không đo lường kết quả']::text[]),
  ((select id from public.industries where slug = 'nhan-su-hanh-chinh'), null, 'behavioral', 'junior',
   'Bạn bảo mật thông tin nhân sự như lương, hồ sơ cá nhân như thế nào?',
   ARRAY['Phân quyền truy cập dữ liệu', 'Không chia sẻ thông tin ngoài phạm vi công việc', 'Tuân thủ quy định bảo vệ dữ liệu cá nhân']::text[],
   ARRAY['Chia sẻ thông tin lương tuỳ tiện', 'Không có ý thức bảo mật']::text[])
on conflict do nothing;

-- dich-vu-khach-hang
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), 'Xử lý khiếu nại', 'technical', 'junior',
   'Hãy trình bày quy trình bạn xử lý một khiếu nại của khách hàng từ lúc tiếp nhận đến khi đóng yêu cầu.',
   ARRAY['Lắng nghe, ghi nhận đầy đủ thông tin khiếu nại', 'Xác minh nguyên nhân, đưa ra giải pháp và thời hạn xử lý', 'Phản hồi khách, theo dõi mức độ hài lòng và đóng yêu cầu']::text[],
   ARRAY['Hứa hẹn không có cơ sở', 'Không theo dõi sau xử lý']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), 'Chỉ số dịch vụ khách hàng', 'technical', 'mid',
   'Các chỉ số CSAT, NPS, FCR và AHT nghĩa là gì? Bạn làm thế nào để cải thiện tỷ lệ giải quyết ngay lần đầu (FCR)?',
   ARRAY['Giải thích đúng CSAT, NPS, FCR, AHT', 'Chuẩn hoá kịch bản và kho kiến thức trả lời', 'Đào tạo nhân viên, phân quyền xử lý và phân tích nguyên nhân gọi lại']::text[],
   ARRAY['Không biết các chỉ số', 'Chỉ tập trung giảm thời gian cuộc gọi']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), 'CRM', 'technical', 'junior',
   'Bạn dùng phần mềm CRM để ghi nhận và theo dõi yêu cầu của khách hàng như thế nào?',
   ARRAY['Tạo ticket đầy đủ thông tin và phân loại yêu cầu', 'Cập nhật trạng thái, chuyển đúng bộ phận', 'Dùng lịch sử khách hàng để cá nhân hoá hỗ trợ']::text[],
   ARRAY['Không ghi nhận lại yêu cầu', 'Không cập nhật trạng thái']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), null, 'situational', 'junior',
   'Khách hàng gọi đến quát mắng, dùng lời lẽ nặng nề vì đơn hàng giao trễ. Bạn xử lý cuộc gọi thế nào?',
   ARRAY['Giữ bình tĩnh, lắng nghe và thể hiện sự đồng cảm', 'Xin lỗi, kiểm tra tình trạng đơn hàng', 'Đưa ra giải pháp và thời hạn cụ thể, theo dõi đến khi hoàn tất']::text[],
   ARRAY['Cãi lại khách', 'Đổ lỗi cho bộ phận khác']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), null, 'situational', 'mid',
   'Khách hàng yêu cầu hoàn tiền nằm ngoài chính sách của công ty. Bạn làm gì?',
   ARRAY['Giải thích chính sách rõ ràng, lịch sự', 'Đề xuất phương án thay thế: đổi hàng, voucher', 'Báo cấp trên nếu trường hợp đặc biệt đáng xem xét']::text[],
   ARRAY['Từ chối cứng nhắc', 'Tự ý hứa hoàn tiền sai quy định']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), null, 'situational', 'mid',
   'Giờ cao điểm, lượng cuộc gọi chờ tăng gấp ba và khách than phiền chờ lâu. Bạn xử lý thế nào?',
   ARRAY['Ưu tiên yêu cầu khẩn cấp', 'Dùng tin nhắn tự động, gọi lại cho khách', 'Đề xuất cải thiện lâu dài: tăng ca, FAQ, chatbot']::text[],
   ARRAY['Rút ngắn cuộc gọi bằng cách bỏ dở', 'Không báo cáo tình trạng']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), null, 'behavioral', 'junior',
   'Kể về một lần bạn biến khách hàng đang không hài lòng thành khách hàng trung thành.',
   ARRAY['Bối cảnh khiếu nại cụ thể', 'Hành động bạn thực hiện', 'Kết quả và phản hồi của khách']::text[],
   ARRAY['Không có ví dụ', 'Kết quả không rõ ràng']::text[]),
  ((select id from public.industries where slug = 'dich-vu-khach-hang'), null, 'behavioral', 'mid',
   'Bạn giữ tinh thần tích cực thế nào khi phải tiếp nhận nhiều phàn nàn mỗi ngày?',
   ARRAY['Tách cảm xúc cá nhân khỏi công việc', 'Có cách tự cân bằng', 'Chia sẻ, học hỏi cùng đồng đội']::text[],
   ARRAY['Dễ căng thẳng, cáu gắt', 'Không có cách tự điều chỉnh']::text[])
on conflict do nothing;

-- thiet-ke-kien-truc
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), 'AutoCAD', 'technical', 'mid',
   'Một bộ hồ sơ bản vẽ kỹ thuật thi công nội thất bạn triển khai bằng AutoCAD gồm những bản vẽ nào?',
   ARRAY['Mặt bằng bố trí, mặt bằng trần, mặt bằng điện nước', 'Mặt đứng, mặt cắt, chi tiết cấu tạo', 'Quy chuẩn layer, tỷ lệ, ghi chú kích thước và vật liệu']::text[],
   ARRAY['Không kể đủ bản vẽ', 'Không nắm quy chuẩn trình bày']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), 'Thiết kế nội thất', 'technical', 'mid',
   'Hãy mô tả quy trình bạn thiết kế một căn hộ từ khi nhận yêu cầu của khách đến khi bàn giao bản vẽ.',
   ARRAY['Khảo sát hiện trạng, tìm hiểu nhu cầu và ngân sách khách', 'Lên concept, moodboard, phương án mặt bằng và phối cảnh 3D', 'Chốt phương án, triển khai bản vẽ kỹ thuật và dự toán']::text[],
   ARRAY['Bỏ qua bước tìm hiểu nhu cầu', 'Không kiểm soát ngân sách']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), 'Photoshop', 'technical', 'junior',
   'Khi thiết kế một ấn phẩm quảng cáo, bạn áp dụng nguyên tắc bố cục, màu sắc và typography như thế nào?',
   ARRAY['Bố cục có điểm nhấn, phân cấp thông tin rõ', 'Màu sắc theo nhận diện thương hiệu, đảm bảo độ tương phản', 'Chọn font phù hợp, xuất file đúng định dạng in hoặc online']::text[],
   ARRAY['Thiết kế theo cảm tính', 'Không quan tâm nhận diện thương hiệu']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), null, 'situational', 'mid',
   'Khách hàng đổi ý sau khi đã chốt concept và muốn làm lại từ đầu. Bạn xử lý thế nào?',
   ARRAY['Tìm hiểu lý do thay đổi', 'Đánh giá ảnh hưởng tiến độ và chi phí, thông báo cho khách', 'Thống nhất lại phạm vi, số lần chỉnh sửa bằng văn bản']::text[],
   ARRAY['Làm lại ngay mà không trao đổi', 'Tỏ thái độ khó chịu']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), null, 'situational', 'junior',
   'Deadline chỉ còn hai ngày nhưng bạn cần đưa ra ba phương án thiết kế. Bạn sắp xếp thế nào?',
   ARRAY['Chia nhỏ công việc và ưu tiên', 'Tận dụng thư viện, template có sẵn', 'Báo trước với quản lý nếu có rủi ro trễ hạn']::text[],
   ARRAY['Làm qua loa cho kịp', 'Im lặng rồi trễ hạn']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), null, 'situational', 'senior',
   'Thiết kế của bạn đẹp nhưng vượt ngân sách của khách 30%. Bạn điều chỉnh ra sao?',
   ARRAY['Xác định hạng mục chi phí lớn', 'Đề xuất vật liệu, giải pháp thay thế tương đương', 'Giữ ý tưởng chủ đạo, trình bày các phương án cho khách chọn']::text[],
   ARRAY['Bỏ qua ngân sách của khách', 'Cắt giảm làm hỏng ý tưởng chính']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), null, 'behavioral', 'mid',
   'Hãy giới thiệu dự án thiết kế tâm đắc nhất trong portfolio của bạn: ý tưởng và vai trò của bạn là gì?',
   ARRAY['Bối cảnh và yêu cầu của dự án', 'Ý tưởng thiết kế và lý do lựa chọn', 'Vai trò cá nhân và kết quả']::text[],
   ARRAY['Không giải thích được ý tưởng', 'Vai trò mơ hồ']::text[]),
  ((select id from public.industries where slug = 'thiet-ke-kien-truc'), null, 'behavioral', 'junior',
   'Bạn tiếp nhận góp ý trái chiều về thiết kế của mình như thế nào?',
   ARRAY['Lắng nghe cởi mở', 'Phân tích góp ý dựa trên mục tiêu dự án', 'Điều chỉnh hoặc bảo vệ ý tưởng bằng lập luận']::text[],
   ARRAY['Bảo thủ, phản ứng tiêu cực', 'Sửa theo mọi ý kiến mà không phân tích']::text[])
on conflict do nothing;

-- khach-san-nha-hang-du-lich
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), 'Lễ tân khách sạn', 'technical', 'junior',
   'Hãy mô tả quy trình check-in và check-out cho khách tại quầy lễ tân.',
   ARRAY['Chào đón, kiểm tra thông tin đặt phòng và giấy tờ tuỳ thân', 'Giới thiệu tiện ích, bàn giao chìa khoá, khai báo lưu trú', 'Check-out: kiểm tra minibar, thanh toán, xin phản hồi của khách']::text[],
   ARRAY['Bỏ qua khai báo lưu trú', 'Thiếu bước kiểm tra phòng khi trả']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), 'Quản lý đặt phòng', 'technical', 'mid',
   'Overbooking là gì? Vì sao khách sạn áp dụng và bạn xử lý thế nào khi khách đến nhưng hết phòng?',
   ARRAY['Giải thích overbooking để bù tỷ lệ huỷ phòng', 'Xin lỗi, sắp xếp phòng tương đương ở khách sạn đối tác, hỗ trợ di chuyển', 'Bồi thường hoặc ưu đãi để giữ thiện cảm']::text[],
   ARRAY['Không biết khái niệm', 'Để khách tự xoay xở']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), 'An toàn vệ sinh thực phẩm', 'technical', 'mid',
   'Trong nhà hàng, bạn đảm bảo an toàn vệ sinh thực phẩm ở những khâu nào?',
   ARRAY['Nhập hàng có nguồn gốc rõ, kiểm tra hạn dùng', 'Bảo quản đúng nhiệt độ, tách sống chín', 'Vệ sinh cá nhân, dụng cụ và lưu mẫu thức ăn']::text[],
   ARRAY['Không nắm quy định cơ bản', 'Xem nhẹ khâu bảo quản']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), null, 'situational', 'junior',
   'Khách phàn nàn tìm thấy tóc trong món ăn và lớn tiếng giữa nhà hàng. Bạn xử lý thế nào?',
   ARRAY['Xin lỗi chân thành, thu hồi và thay món ngay', 'Mời khách ra khu vực riêng nếu cần, giữ bình tĩnh', 'Báo quản lý, có hình thức bù đắp và kiểm tra lại quy trình bếp']::text[],
   ARRAY['Cãi lại hoặc nghi ngờ khách', 'Không báo cáo']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), null, 'situational', 'mid',
   'Một đoàn khách đến sớm hơn giờ nhận phòng 5 tiếng và muốn nhận phòng ngay. Bạn làm gì?',
   ARRAY['Kiểm tra phòng trống, ưu tiên dọn phòng cho đoàn', 'Gửi hành lý, mời nghỉ ở sảnh, gợi ý dịch vụ', 'Thông báo rõ thời gian dự kiến có phòng']::text[],
   ARRAY['Từ chối cứng nhắc', 'Hứa hẹn không thực hiện được']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), null, 'situational', 'mid',
   'Khách để lại đánh giá 1 sao trên mạng vì thái độ nhân viên. Bạn phản hồi ra sao?',
   ARRAY['Phản hồi công khai lịch sự, cầu thị', 'Liên hệ riêng khách để tìm hiểu và bù đắp', 'Xác minh nội bộ, đào tạo lại nhân viên']::text[],
   ARRAY['Phản bác gay gắt trên mạng', 'Phớt lờ đánh giá']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), null, 'behavioral', 'junior',
   'Kể về lần bạn làm khách hàng hài lòng vượt mong đợi.',
   ARRAY['Tình huống cụ thể', 'Hành động chủ động của bạn', 'Phản hồi của khách']::text[],
   ARRAY['Không có ví dụ', 'Chỉ làm đúng việc tối thiểu']::text[]),
  ((select id from public.industries where slug = 'khach-san-nha-hang-du-lich'), null, 'behavioral', 'junior',
   'Công việc ngành dịch vụ thường làm ca, cuối tuần và lễ Tết. Bạn sắp xếp thế nào?',
   ARRAY['Hiểu và chấp nhận đặc thù ngành', 'Có kế hoạch cân bằng cá nhân', 'Cam kết gắn bó']::text[],
   ARRAY['Không chấp nhận làm ca', 'Trả lời né tránh']::text[])
on conflict do nothing;

-- y-te-duoc
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'y-te-duoc'), 'Tư vấn thuốc', 'technical', 'junior',
   'Nguyên tắc 5 đúng khi dùng thuốc là gì? Bạn tư vấn sử dụng thuốc cho người bệnh như thế nào?',
   ARRAY['Đúng người bệnh, đúng thuốc, đúng liều, đúng đường dùng, đúng thời gian', 'Hỏi tiền sử dị ứng, bệnh kèm theo, thuốc đang dùng', 'Hướng dẫn cách dùng, tác dụng phụ và khi nào cần tái khám']::text[],
   ARRAY['Không kể đủ 5 đúng', 'Không hỏi tiền sử dị ứng']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), 'GPP', 'technical', 'mid',
   'Tiêu chuẩn GPP (Thực hành tốt nhà thuốc) gồm những yêu cầu chính nào?',
   ARRAY['Nhân sự có chứng chỉ hành nghề phù hợp', 'Cơ sở vật chất, bảo quản thuốc đúng nhiệt độ, độ ẩm', 'Hồ sơ sổ sách, bán thuốc kê đơn đúng quy định']::text[],
   ARRAY['Không nắm tiêu chuẩn', 'Xem nhẹ bán thuốc kê đơn']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), 'Quản lý kho thuốc', 'technical', 'mid',
   'Bạn quản lý kho thuốc và kiểm soát hạn dùng như thế nào?',
   ARRAY['Áp dụng FEFO: hết hạn trước xuất trước', 'Theo dõi nhiệt độ, độ ẩm và kiểm kê định kỳ', 'Cảnh báo thuốc cận hạn, xử lý thuốc hết hạn theo quy định']::text[],
   ARRAY['Không biết FEFO', 'Không theo dõi hạn dùng']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), null, 'situational', 'junior',
   'Khách muốn mua kháng sinh nhưng không có đơn của bác sĩ. Bạn xử lý thế nào?',
   ARRAY['Giải thích quy định kháng sinh là thuốc kê đơn', 'Cảnh báo nguy cơ kháng thuốc', 'Khuyên khách đi khám, tư vấn biện pháp hỗ trợ phù hợp']::text[],
   ARRAY['Bán luôn để giữ khách', 'Từ chối thiếu tế nhị']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), null, 'situational', 'mid',
   'Bạn phát hiện đã giao nhầm thuốc cho người bệnh sau khi họ rời đi. Bạn làm gì?',
   ARRAY['Liên hệ người bệnh ngay để ngừng dùng và đổi thuốc', 'Báo cáo người phụ trách', 'Ghi nhận sự cố và cải tiến quy trình kiểm tra chéo']::text[],
   ARRAY['Giấu sự cố', 'Chờ người bệnh tự quay lại']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), null, 'situational', 'mid',
   'Người nhà bệnh nhân nóng nảy, lớn tiếng vì phải chờ lâu. Bạn ứng xử thế nào?',
   ARRAY['Giữ bình tĩnh, lắng nghe và đồng cảm', 'Giải thích rõ quy trình, thời gian chờ dự kiến', 'Hỗ trợ trong khả năng, báo người phụ trách nếu cần']::text[],
   ARRAY['Cãi lại', 'Bỏ mặc người nhà']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), null, 'behavioral', 'junior',
   'Vì sao bạn chọn ngành y dược, và bạn giữ đạo đức nghề nghiệp như thế nào?',
   ARRAY['Động lực chọn nghề rõ ràng', 'Đặt an toàn người bệnh lên hàng đầu', 'Tuân thủ quy định chuyên môn']::text[],
   ARRAY['Chỉ vì thu nhập', 'Không nhắc đến an toàn người bệnh']::text[]),
  ((select id from public.industries where slug = 'y-te-duoc'), null, 'behavioral', 'mid',
   'Kể về một tình huống áp lực trong công việc chuyên môn và cách bạn vượt qua.',
   ARRAY['Bối cảnh cụ thể', 'Cách xử lý giữ đúng chuyên môn', 'Bài học rút ra']::text[],
   ARRAY['Không có ví dụ', 'Xử lý vi phạm quy định']::text[])
on conflict do nothing;

-- xay-dung
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'xay-dung'), 'Dự toán', 'technical', 'mid',
   'Bạn lập dự toán cho một công trình dựa trên những căn cứ nào?',
   ARRAY['Hồ sơ thiết kế và bóc tách khối lượng', 'Định mức, đơn giá vật liệu, nhân công, máy thi công', 'Chi phí chung, dự phòng và cập nhật giá thị trường']::text[],
   ARRAY['Ước lượng theo cảm tính', 'Không nắm định mức']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), 'Giám sát thi công', 'technical', 'mid',
   'Trước khi đổ bê tông sàn, bạn nghiệm thu cốt thép và cốp pha như thế nào?',
   ARRAY['Kiểm tra chủng loại, đường kính, khoảng cách, chiều dài nối cốt thép', 'Kiểm tra lớp bê tông bảo vệ, độ kín khít và cao độ cốp pha', 'Lập biên bản nghiệm thu có các bên ký xác nhận']::text[],
   ARRAY['Bỏ qua nghiệm thu', 'Không kiểm tra theo bản vẽ']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), 'An toàn lao động', 'technical', 'junior',
   'Những biện pháp an toàn bắt buộc khi làm việc trên cao ở công trường là gì?',
   ARRAY['Dây đai an toàn, lan can, lưới chống rơi', 'Kiểm tra giàn giáo trước khi sử dụng', 'Huấn luyện an toàn và giám sát việc tuân thủ']::text[],
   ARRAY['Không kể được biện pháp', 'Xem nhẹ an toàn']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), null, 'situational', 'mid',
   'Dự báo mưa lớn đúng ngày kế hoạch đổ bê tông. Bạn xử lý như thế nào?',
   ARRAY['Cân nhắc dời lịch, báo nhà cung cấp bê tông', 'Nếu vẫn đổ: chuẩn bị bạt che, xử lý mạch ngừng', 'Thống nhất với tư vấn giám sát và chủ đầu tư']::text[],
   ARRAY['Vẫn đổ bình thường không che chắn', 'Không báo các bên']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), null, 'situational', 'mid',
   'Nhà thầu phụ thi công sai bản vẽ một hạng mục. Bạn làm gì?',
   ARRAY['Dừng thi công hạng mục sai, lập biên bản', 'Yêu cầu khắc phục theo đúng thiết kế', 'Báo cáo chỉ huy trưởng, đánh giá ảnh hưởng tiến độ và chi phí']::text[],
   ARRAY['Bỏ qua cho kịp tiến độ', 'Tự ý sửa thiết kế']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), null, 'situational', 'senior',
   'Chủ đầu tư muốn thay đổi thiết kế khi công trình đang thi công. Bạn xử lý ra sao?',
   ARRAY['Đánh giá ảnh hưởng kết cấu, tiến độ, chi phí', 'Yêu cầu văn bản thay đổi và bản vẽ điều chỉnh được duyệt', 'Cập nhật hợp đồng, dự toán phát sinh']::text[],
   ARRAY['Làm theo lời nói, không có văn bản', 'Không tính chi phí phát sinh']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), null, 'behavioral', 'mid',
   'Kể về công trình bạn tham gia mà bạn thấy tự hào nhất và vai trò của bạn.',
   ARRAY['Quy mô công trình', 'Nhiệm vụ cụ thể của bạn', 'Khó khăn và kết quả']::text[],
   ARRAY['Vai trò mơ hồ', 'Không có kết quả cụ thể']::text[]),
  ((select id from public.industries where slug = 'xay-dung'), null, 'behavioral', 'junior',
   'Bạn phối hợp với đội thợ và các bên liên quan trên công trường như thế nào?',
   ARRAY['Giao tiếp rõ ràng, tôn trọng', 'Họp giao ban, phân công cụ thể', 'Giải quyết mâu thuẫn dựa trên bản vẽ và quy định']::text[],
   ARRAY['Áp đặt, thiếu tôn trọng', 'Thiếu phối hợp']::text[])
on conflict do nothing;

-- dien-dien-tu-vien-thong
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), 'Thiết bị đóng cắt', 'technical', 'mid',
   'Hãy phân biệt MCB, MCCB, RCBO và cách bạn chọn thiết bị bảo vệ cho một tuyến cáp.',
   ARRAY['MCB, MCCB bảo vệ quá tải và ngắn mạch; RCBO có thêm chống dòng rò', 'Chọn theo dòng định mức, dòng cắt ngắn mạch và tiết diện cáp', 'Đảm bảo phối hợp bảo vệ, chọn lọc']::text[],
   ARRAY['Nhầm công dụng các thiết bị', 'Chọn thiết bị không theo tính toán']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), 'PLC', 'technical', 'mid',
   'Bạn lập trình PLC điều khiển một băng tải có cảm biến và nút dừng khẩn cấp như thế nào?',
   ARRAY['Xác định đầu vào ra: cảm biến, nút nhấn, động cơ', 'Viết chương trình ladder có khoá liên động', 'Ưu tiên dừng khẩn cấp, chạy thử và mô phỏng trước khi đưa vào vận hành']::text[],
   ARRAY['Không có khoá an toàn', 'Không chạy thử']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), 'Mạng viễn thông', 'technical', 'mid',
   'Khi trạm phát sóng mất tín hiệu, quy trình bạn đo kiểm và khoanh vùng lỗi như thế nào?',
   ARRAY['Kiểm tra cảnh báo trên hệ thống giám sát', 'Kiểm tra nguồn điện, truyền dẫn, thiết bị vô tuyến', 'Dùng thiết bị đo, xử lý và báo cáo sự cố']::text[],
   ARRAY['Thay thiết bị bừa', 'Không có quy trình khoanh vùng']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), null, 'situational', 'mid',
   'Toàn bộ xưởng bị mất điện giữa ca sản xuất. Bạn xử lý như thế nào?',
   ARRAY['Đảm bảo an toàn, ngắt thiết bị quan trọng', 'Kiểm tra nguồn lưới, tủ tổng, máy phát dự phòng', 'Khắc phục, khôi phục theo trình tự và báo cáo nguyên nhân']::text[],
   ARRAY['Đóng điện lại khi chưa rõ nguyên nhân', 'Không báo cáo']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), null, 'situational', 'junior',
   'Khách hàng phản ánh mạng internet chập chờn liên tục. Bạn xử lý thế nào?',
   ARRAY['Hỏi thông tin, kiểm tra từ xa', 'Kiểm tra thiết bị, cáp, tín hiệu tại nhà khách', 'Khắc phục, hướng dẫn khách và theo dõi sau xử lý']::text[],
   ARRAY['Đổ lỗi cho thiết bị của khách', 'Không theo dõi sau xử lý']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), null, 'situational', 'senior',
   'Một loại thiết bị liên tục hỏng sau vài tuần vận hành. Bạn điều tra nguyên nhân thế nào?',
   ARRAY['Thu thập dữ liệu lỗi, điều kiện vận hành', 'Phân tích nguyên nhân gốc: nguồn, nhiệt độ, lắp đặt, chất lượng lô', 'Đề xuất khắc phục và làm việc với nhà cung cấp']::text[],
   ARRAY['Chỉ thay mới liên tục', 'Không phân tích nguyên nhân']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), null, 'behavioral', 'mid',
   'Kể về một sự cố kỹ thuật phức tạp bạn đã xử lý thành công.',
   ARRAY['Mô tả sự cố', 'Các bước chẩn đoán', 'Kết quả và bài học']::text[],
   ARRAY['Không có ví dụ', 'Không nêu được cách chẩn đoán']::text[]),
  ((select id from public.industries where slug = 'dien-dien-tu-vien-thong'), null, 'behavioral', 'junior',
   'Bạn đảm bảo an toàn điện cho bản thân và đồng đội khi làm việc như thế nào?',
   ARRAY['Cắt điện, treo biển, kiểm tra không còn điện', 'Dùng bảo hộ đúng quy định', 'Không làm việc một mình với điện áp nguy hiểm']::text[],
   ARRAY['Chủ quan, làm khi có điện', 'Không dùng bảo hộ']::text[])
on conflict do nothing;

-- bat-dong-san
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'bat-dong-san'), 'Pháp lý bất động sản', 'technical', 'mid',
   'Khi tư vấn một căn hộ dự án, bạn kiểm tra pháp lý dự án gồm những giấy tờ nào?',
   ARRAY['Quyết định chủ trương đầu tư, giấy phép xây dựng', 'Giấy chứng nhận quyền sử dụng đất, bảo lãnh ngân hàng', 'Văn bản đủ điều kiện mở bán nhà ở hình thành trong tương lai']::text[],
   ARRAY['Không nắm giấy tờ pháp lý', 'Cam kết pháp lý khi chưa kiểm tra']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), 'Tìm kiếm khách hàng', 'technical', 'junior',
   'Nếu công ty không cấp data, bạn tìm nguồn khách hàng mua bất động sản bằng cách nào?',
   ARRAY['Kênh online: Facebook, Zalo, sàn bất động sản, quảng cáo', 'Kênh offline: sự kiện, dẫn khách tham quan, giới thiệu từ khách cũ', 'Quản lý và chăm sóc data khách hàng có hệ thống']::text[],
   ARRAY['Chỉ chờ công ty cấp data', 'Spam tin nhắn tràn lan']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), 'Tư vấn tài chính mua nhà', 'technical', 'mid',
   'Bạn trình bày phương án tài chính cho khách mua căn hộ 3 tỷ như thế nào: vay ngân hàng, tiến độ thanh toán?',
   ARRAY['Tỷ lệ vay, lãi suất ưu đãi và thả nổi, thời hạn vay', 'Số tiền trả góp hằng tháng, chính sách hỗ trợ của chủ đầu tư', 'Đánh giá khả năng tài chính của khách']::text[],
   ARRAY['Không tính được tiền trả góp', 'Che giấu lãi suất thả nổi']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), null, 'situational', 'mid',
   'Khách đã đặt cọc nhưng muốn huỷ vì nghe tin dự án chậm pháp lý. Bạn xử lý thế nào?',
   ARRAY['Lắng nghe lo ngại, kiểm tra thông tin pháp lý chính thức', 'Cung cấp văn bản, tiến độ pháp lý minh bạch', 'Tư vấn trung thực quyền lợi và điều khoản cọc, báo quản lý']::text[],
   ARRAY['Hứa hẹn sai sự thật để giữ cọc', 'Gây áp lực, doạ mất cọc']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), null, 'situational', 'junior',
   'Khách hỏi về quy hoạch khu vực mà bạn chưa chắc chắn thông tin. Bạn trả lời thế nào?',
   ARRAY['Thừa nhận chưa chắc, hẹn thời gian phản hồi', 'Kiểm tra nguồn chính thức: cơ quan quản lý, bản đồ quy hoạch', 'Cung cấp thông tin có căn cứ']::text[],
   ARRAY['Trả lời bừa cho qua', 'Né tránh câu hỏi']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), null, 'situational', 'mid',
   'Hai khách cùng muốn mua một căn đẹp nhất trong giỏ hàng. Bạn xử lý như thế nào cho công bằng?',
   ARRAY['Áp dụng đúng quy định giữ chỗ và thứ tự đặt cọc', 'Minh bạch thông tin với cả hai khách', 'Tư vấn căn thay thế phù hợp cho khách còn lại']::text[],
   ARRAY['Ưu tiên theo quan hệ cá nhân', 'Giấu thông tin']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), null, 'behavioral', 'mid',
   'Kể về giao dịch bất động sản khó nhất bạn từng chốt thành công.',
   ARRAY['Bối cảnh và khó khăn', 'Cách bạn thuyết phục, xử lý phản đối', 'Giá trị giao dịch và bài học']::text[],
   ARRAY['Không có ví dụ', 'Chốt nhờ cam kết sai sự thật']::text[]),
  ((select id from public.industries where slug = 'bat-dong-san'), null, 'behavioral', 'junior',
   'Nghề môi giới có thu nhập không ổn định và áp lực doanh số cao. Bạn chuẩn bị tinh thần thế nào?',
   ARRAY['Hiểu đặc thù hoa hồng theo giao dịch', 'Có kế hoạch tài chính cá nhân và mục tiêu', 'Kiên trì, học hỏi liên tục']::text[],
   ARRAY['Kỳ vọng thu nhập nhanh, dễ', 'Dễ bỏ cuộc']::text[])
on conflict do nothing;

-- co-khi-che-tao
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'co-khi-che-tao'), 'Đọc bản vẽ kỹ thuật', 'technical', 'junior',
   'Trên bản vẽ chi tiết ghi Ø20H7/g6. Ký hiệu này có ý nghĩa gì và ảnh hưởng thế nào đến gia công?',
   ARRAY['Kích thước danh nghĩa 20 và kiểu lắp ghép lỗ cơ bản H7 với trục g6', 'Đây là lắp lỏng, xác định dung sai cho phép', 'Chọn phương pháp gia công, dụng cụ đo phù hợp để đạt dung sai']::text[],
   ARRAY['Không đọc được ký hiệu dung sai', 'Không biết kiểu lắp ghép']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), 'Bảo trì máy', 'technical', 'mid',
   'Bạn xây dựng kế hoạch bảo trì phòng ngừa cho dây chuyền máy như thế nào?',
   ARRAY['Lập danh sách thiết bị, tần suất bảo trì theo khuyến cáo', 'Checklist kiểm tra, bôi trơn, thay thế định kỳ', 'Ghi nhận lịch sử hỏng hóc, theo dõi chỉ số MTBF, OEE']::text[],
   ARRAY['Chỉ sửa khi hỏng', 'Không lưu lịch sử bảo trì']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), 'CNC', 'technical', 'mid',
   'Khi gia công CNC một chi tiết mới, bạn chọn chế độ cắt và kiểm soát chất lượng thế nào?',
   ARRAY['Chọn dao, tốc độ quay, bước tiến, chiều sâu cắt theo vật liệu', 'Chạy thử, mô phỏng chương trình, kiểm tra sản phẩm đầu tiên', 'Đo kiểm định kỳ, bù mòn dao']::text[],
   ARRAY['Chạy hàng loạt không chạy thử', 'Không đo kiểm']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), null, 'situational', 'mid',
   'Máy chính dừng đột ngột giữa ca khi đơn hàng đang gấp. Bạn xử lý thế nào?',
   ARRAY['Đảm bảo an toàn, chẩn đoán nhanh nguyên nhân', 'Huy động phụ tùng, chuyển sản xuất sang máy khác nếu có', 'Báo cáo tiến độ và phân tích nguyên nhân gốc để phòng ngừa']::text[],
   ARRAY['Sửa tạm bỏ qua an toàn', 'Không báo cáo']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), null, 'situational', 'mid',
   'Phát hiện một loạt chi tiết gia công sai kích thước. Bạn làm gì?',
   ARRAY['Dừng sản xuất, khoanh vùng lô hàng lỗi', 'Tìm nguyên nhân: chương trình, dao, gá, máy', 'Khắc phục và kiểm tra lại toàn bộ lô']::text[],
   ARRAY['Tiếp tục sản xuất', 'Trộn hàng lỗi vào hàng đạt']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), null, 'situational', 'junior',
   'Bạn thấy đồng nghiệp tháo che chắn an toàn của máy để làm nhanh hơn. Bạn phản ứng thế nào?',
   ARRAY['Nhắc nhở ngay, giải thích nguy cơ tai nạn', 'Báo tổ trưởng nếu vẫn tái diễn', 'Đề xuất cải tiến nếu thao tác bất tiện']::text[],
   ARRAY['Làm ngơ', 'Làm theo đồng nghiệp']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), null, 'behavioral', 'mid',
   'Kể về một cải tiến kỹ thuật bạn đề xuất giúp tăng năng suất hoặc giảm lỗi.',
   ARRAY['Vấn đề ban đầu', 'Giải pháp cải tiến', 'Kết quả đo được']::text[],
   ARRAY['Không có ví dụ', 'Không có số liệu']::text[]),
  ((select id from public.industries where slug = 'co-khi-che-tao'), null, 'behavioral', 'junior',
   'Bạn học hỏi và cập nhật kỹ năng vận hành máy móc mới như thế nào?',
   ARRAY['Đọc tài liệu hướng dẫn', 'Học từ người có kinh nghiệm', 'Thực hành dưới giám sát']::text[],
   ARRAY['Tự mày mò bỏ qua hướng dẫn', 'Ngại học']::text[])
on conflict do nothing;

-- van-tai-logistics
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'van-tai-logistics'), 'Incoterms', 'technical', 'mid',
   'Hãy phân biệt điều kiện FOB và CIF theo Incoterms 2020. Khi nào nên chọn điều kiện nào?',
   ARRAY['FOB: người bán giao hàng lên tàu, người mua chịu cước và bảo hiểm', 'CIF: người bán trả cước và mua bảo hiểm tới cảng đích', 'Điểm chuyển giao rủi ro và lựa chọn theo lợi thế thuê tàu']::text[],
   ARRAY['Nhầm điểm chuyển rủi ro', 'Không nắm Incoterms']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), 'Khai báo hải quan', 'technical', 'mid',
   'Bộ chứng từ xuất khẩu cơ bản gồm những gì? Bạn khai báo hải quan một lô hàng như thế nào?',
   ARRAY['Hợp đồng, hoá đơn thương mại, phiếu đóng gói, vận đơn, C/O', 'Khai tờ khai trên hệ thống VNACCS, xác định mã HS', 'Theo dõi phân luồng xanh, vàng, đỏ và thông quan']::text[],
   ARRAY['Không biết mã HS', 'Thiếu chứng từ cơ bản']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), 'Quản lý kho', 'technical', 'junior',
   'Bạn quản lý nhập, xuất, tồn kho như thế nào để hạn chế sai lệch?',
   ARRAY['Áp dụng FIFO hoặc FEFO', 'Sắp xếp vị trí, mã hàng, quét mã vạch', 'Kiểm kê định kỳ, đối chiếu sổ sách và thực tế']::text[],
   ARRAY['Không kiểm kê', 'Nhập xuất không chứng từ']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), null, 'situational', 'mid',
   'Lô hàng nhập khẩu bị giữ tại cảng vì thiếu chứng từ, khách hàng đang cần gấp. Bạn xử lý thế nào?',
   ARRAY['Xác định chứng từ thiếu, liên hệ ngay nhà cung cấp và hải quan', 'Tính chi phí lưu kho, lưu container phát sinh', 'Cập nhật tình hình thường xuyên cho khách']::text[],
   ARRAY['Không thông báo khách', 'Không kiểm soát chi phí phát sinh']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), null, 'situational', 'junior',
   'Xe giao hàng cho khách hàng lớn bị trễ 4 tiếng do tắc đường. Bạn làm gì?',
   ARRAY['Thông báo ngay cho khách, cập nhật thời gian dự kiến', 'Tìm phương án thay thế nếu có', 'Rút kinh nghiệm lộ trình và thời gian dự phòng']::text[],
   ARRAY['Im lặng đến khi khách gọi', 'Đổ lỗi cho tài xế']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), null, 'situational', 'mid',
   'Kiểm kê cuối tháng phát hiện chênh lệch tồn kho 3% giá trị. Bạn điều tra thế nào?',
   ARRAY['Đối chiếu chứng từ nhập xuất, kiểm tra nhầm mã', 'Kiểm tra lại quy trình, camera, phân quyền', 'Lập biên bản, báo cáo và cải thiện quy trình']::text[],
   ARRAY['Điều chỉnh số liệu cho khớp', 'Không tìm nguyên nhân']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), null, 'behavioral', 'mid',
   'Kể về lần bạn tối ưu chi phí vận chuyển hoặc thời gian giao hàng.',
   ARRAY['Vấn đề ban đầu', 'Giải pháp: gom hàng, đổi tuyến, đổi nhà vận tải', 'Kết quả bằng số liệu']::text[],
   ARRAY['Không có số liệu', 'Không có ví dụ']::text[]),
  ((select id from public.industries where slug = 'van-tai-logistics'), null, 'behavioral', 'junior',
   'Bạn làm việc với nhiều bên (nhà xe, hải quan, khách hàng) cùng lúc như thế nào?',
   ARRAY['Giao tiếp rõ ràng, theo dõi đầu việc', 'Ưu tiên theo thời hạn', 'Lưu vết trao đổi']::text[],
   ARRAY['Quên việc, bỏ sót', 'Giao tiếp thiếu chuyên nghiệp']::text[])
on conflict do nothing;

-- san-xuat-qa-qc
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), 'Kiểm soát chất lượng', 'technical', 'mid',
   'Bạn đã dùng những công cụ nào trong 7 công cụ QC? Hãy lấy ví dụ dùng biểu đồ Pareto hoặc xương cá.',
   ARRAY['Kể được các công cụ: Pareto, xương cá, biểu đồ kiểm soát, phiếu kiểm tra, histogram', 'Ví dụ cụ thể dùng Pareto để ưu tiên lỗi hoặc xương cá tìm nguyên nhân', 'Hành động khắc phục sau phân tích']::text[],
   ARRAY['Không biết công cụ nào', 'Không có ví dụ thực tế']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), 'ISO 9001', 'technical', 'mid',
   'ISO 9001 yêu cầu doanh nghiệp những gì? Bạn chuẩn bị cho một đợt đánh giá như thế nào?',
   ARRAY['Tiếp cận theo quá trình, quản lý rủi ro, cải tiến liên tục', 'Kiểm soát tài liệu, hồ sơ, đánh giá nội bộ', 'Rà soát điểm không phù hợp và hành động khắc phục trước đợt đánh giá']::text[],
   ARRAY['Chỉ làm hồ sơ đối phó', 'Không hiểu mục đích tiêu chuẩn']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), '5S', 'technical', 'junior',
   '5S gồm những bước nào? Bạn triển khai 5S tại một khu vực sản xuất ra sao?',
   ARRAY['Sàng lọc, sắp xếp, sạch sẽ, săn sóc, sẵn sàng', 'Đánh dấu vị trí, loại bỏ vật không cần thiết', 'Đánh giá định kỳ và duy trì']::text[],
   ARRAY['Không kể đủ 5 bước', 'Làm một lần rồi bỏ']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), null, 'situational', 'mid',
   'Khách hàng phản hồi một lô hàng bị lỗi sau khi đã xuất đi. Bạn xử lý thế nào?',
   ARRAY['Khoanh vùng lô hàng, cách ly hàng tồn liên quan', 'Phân tích nguyên nhân gốc (5 Why), lập báo cáo 8D', 'Hành động khắc phục, phòng ngừa và phản hồi khách']::text[],
   ARRAY['Đổ lỗi cho khách', 'Không tìm nguyên nhân gốc']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), null, 'situational', 'mid',
   'Quản lý sản xuất muốn bỏ qua một bước kiểm tra để kịp sản lượng. Bạn phản hồi thế nào?',
   ARRAY['Giải thích rủi ro lỗi lọt đến khách', 'Đề xuất phương án tăng tốc mà vẫn đảm bảo kiểm soát', 'Báo cáo cấp trên nếu không thống nhất']::text[],
   ARRAY['Đồng ý bỏ qua kiểm tra', 'Phản đối gay gắt không đưa giải pháp']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), null, 'situational', 'senior',
   'Khách hàng báo sẽ audit nhà máy đột xuất vào tuần sau. Bạn chuẩn bị những gì?',
   ARRAY['Rà soát hồ sơ chất lượng, quy trình và điểm không phù hợp', 'Kiểm tra hiện trường, 5S, an toàn', 'Phân công người phụ trách tiếp đoàn, trả lời đúng thực tế']::text[],
   ARRAY['Làm hồ sơ giả đối phó', 'Không chuẩn bị']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), null, 'behavioral', 'mid',
   'Kể về một dự án cải tiến chất lượng bạn tham gia và kết quả đạt được.',
   ARRAY['Vấn đề chất lượng ban đầu', 'Phương pháp cải tiến', 'Kết quả: tỷ lệ lỗi giảm bao nhiêu']::text[],
   ARRAY['Không có số liệu', 'Vai trò mơ hồ']::text[]),
  ((select id from public.industries where slug = 'san-xuat-qa-qc'), null, 'behavioral', 'junior',
   'Bạn giữ sự khách quan thế nào khi đánh giá lỗi của bộ phận khác?',
   ARRAY['Dựa trên dữ liệu và tiêu chuẩn', 'Trao đổi tôn trọng', 'Tập trung giải pháp, không đổ lỗi']::text[],
   ARRAY['Thiên vị', 'Đổ lỗi cá nhân']::text[])
on conflict do nothing;

-- giao-duc-dao-tao
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), 'Soạn giáo án', 'technical', 'mid',
   'Bạn thiết kế một bài giảng 90 phút như thế nào để đạt mục tiêu bài học?',
   ARRAY['Xác định mục tiêu bài học đo lường được', 'Chia hoạt động: khởi động, kiến thức mới, luyện tập, củng cố', 'Phương pháp đánh giá cuối buổi']::text[],
   ARRAY['Không có mục tiêu rõ', 'Chỉ giảng lý thuyết một chiều']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), 'Phương pháp giảng dạy', 'technical', 'mid',
   'Bạn áp dụng phương pháp giảng dạy tích cực nào để học viên tham gia nhiều hơn?',
   ARRAY['Hoạt động nhóm, thảo luận, dự án', 'Đặt câu hỏi gợi mở, học qua tình huống thực tế', 'Phản hồi thường xuyên cho học viên']::text[],
   ARRAY['Chỉ đọc chép', 'Không tương tác với học viên']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), 'Đánh giá học viên', 'technical', 'junior',
   'Bạn đánh giá sự tiến bộ của học viên bằng những cách nào?',
   ARRAY['Đánh giá thường xuyên qua bài tập, câu hỏi nhanh', 'Kiểm tra định kỳ theo tiêu chí rõ ràng', 'Theo dõi tiến bộ và phản hồi cho học viên, phụ huynh']::text[],
   ARRAY['Chỉ dựa vào một bài thi cuối', 'Không phản hồi']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), null, 'situational', 'junior',
   'Một học viên liên tục mất tập trung và gây ảnh hưởng đến cả lớp. Bạn xử lý thế nào?',
   ARRAY['Nhắc nhở khéo léo, không làm học viên mất mặt', 'Trao đổi riêng để tìm hiểu nguyên nhân', 'Điều chỉnh hoạt động, phối hợp phụ huynh nếu cần']::text[],
   ARRAY['La mắng trước lớp', 'Bỏ mặc']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), null, 'situational', 'mid',
   'Phụ huynh phàn nàn con học ở lớp bạn nhưng điểm vẫn thấp. Bạn phản hồi thế nào?',
   ARRAY['Lắng nghe, cung cấp dữ liệu tiến bộ cụ thể', 'Phân tích điểm yếu của học viên', 'Đề xuất kế hoạch hỗ trợ và theo dõi']::text[],
   ARRAY['Đổ lỗi cho học viên', 'Phản ứng phòng thủ']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), null, 'situational', 'mid',
   'Lớp học có trình độ học viên chênh lệch nhiều. Bạn tổ chức lớp như thế nào?',
   ARRAY['Phân hoá nhiệm vụ theo trình độ', 'Chia nhóm hỗ trợ lẫn nhau', 'Bài tập mở rộng cho học viên khá, hỗ trợ thêm cho học viên yếu']::text[],
   ARRAY['Dạy một kiểu cho tất cả', 'Bỏ quên học viên yếu']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), null, 'behavioral', 'junior',
   'Vì sao bạn chọn nghề giáo dục và điều gì khiến bạn gắn bó?',
   ARRAY['Động lực rõ ràng', 'Yêu thích sự tiến bộ của học viên', 'Tinh thần học hỏi liên tục']::text[],
   ARRAY['Chỉ vì công việc ổn định', 'Không có động lực rõ ràng']::text[]),
  ((select id from public.industries where slug = 'giao-duc-dao-tao'), null, 'behavioral', 'mid',
   'Kể về một học viên bạn đã giúp tiến bộ rõ rệt.',
   ARRAY['Tình trạng ban đầu', 'Cách bạn hỗ trợ', 'Kết quả cụ thể']::text[],
   ARRAY['Không có ví dụ', 'Kết quả mơ hồ']::text[])
on conflict do nothing;

-- lao-dong-pho-thong
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), 'An toàn lao động', 'technical', 'junior',
   'Khi làm việc ở xưởng hoặc kho, bạn phải tuân thủ những quy định an toàn nào?',
   ARRAY['Mang đồ bảo hộ đúng quy định', 'Tuân thủ biển báo, quy trình vận hành', 'Báo ngay khi thấy nguy cơ mất an toàn']::text[],
   ARRAY['Chủ quan, không mang bảo hộ', 'Không biết quy định']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), 'Sắp xếp kho hàng', 'technical', 'junior',
   'Bạn sắp xếp và bảo quản hàng hoá trong kho như thế nào để tránh hư hỏng, nhầm lẫn?',
   ARRAY['Xếp theo khu vực, mã hàng, hàng nặng ở dưới', 'Nhập trước xuất trước', 'Kiểm tra, ghi chép khi nhập xuất']::text[],
   ARRAY['Xếp tuỳ tiện', 'Không ghi chép']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), 'Vận hành máy', 'technical', 'junior',
   'Trước khi bắt đầu ca làm việc với máy móc, bạn kiểm tra những gì?',
   ARRAY['Kiểm tra tình trạng máy, dầu, nguồn điện', 'Kiểm tra thiết bị an toàn, nút dừng khẩn cấp', 'Báo tổ trưởng nếu phát hiện bất thường']::text[],
   ARRAY['Chạy máy ngay không kiểm tra', 'Tự sửa máy khi không được phân công']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), null, 'situational', 'junior',
   'Bạn thấy đồng nghiệp làm sai quy trình có thể gây nguy hiểm. Bạn làm gì?',
   ARRAY['Nhắc nhở đồng nghiệp ngay', 'Báo tổ trưởng nếu vẫn tiếp diễn', 'Không làm theo cách sai']::text[],
   ARRAY['Làm ngơ', 'Làm theo cho nhanh']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), null, 'situational', 'junior',
   'Trong ca làm, bạn được giao lượng việc vượt quá khả năng hoàn thành. Bạn xử lý thế nào?',
   ARRAY['Báo tổ trưởng sớm', 'Sắp xếp việc ưu tiên', 'Đề xuất hỗ trợ hoặc tăng ca hợp lý']::text[],
   ARRAY['Im lặng rồi làm không xong', 'Làm ẩu cho kịp']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), null, 'situational', 'junior',
   'Hàng hoá bị hư hỏng trong lúc bạn vận chuyển. Bạn làm gì?',
   ARRAY['Báo ngay cho quản lý, không che giấu', 'Ghi nhận tình trạng, chụp ảnh', 'Rút kinh nghiệm cách vận chuyển']::text[],
   ARRAY['Giấu hàng hư', 'Đổ lỗi người khác']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), null, 'behavioral', 'junior',
   'Bạn có sẵn sàng làm ca, tăng ca khi công ty cần không? Bạn đảm bảo đi làm đúng giờ thế nào?',
   ARRAY['Sẵn sàng khi có kế hoạch trước', 'Có phương tiện, sắp xếp thời gian hợp lý', 'Cam kết đúng giờ']::text[],
   ARRAY['Thường xuyên đi trễ', 'Không chấp nhận tăng ca']::text[]),
  ((select id from public.industries where slug = 'lao-dong-pho-thong'), null, 'behavioral', 'junior',
   'Vì sao bạn muốn làm công việc này và dự định gắn bó bao lâu?',
   ARRAY['Lý do rõ ràng', 'Mong muốn học hỏi, phát triển', 'Dự định gắn bó cụ thể']::text[],
   ARRAY['Không có lý do', 'Chỉ làm tạm thời']::text[])
on conflict do nothing;

-- Câu hỏi hành vi chung (không gắn ngành)
insert into public.interview_questions (industry_id, skill_tag, question_type, difficulty, question, expected, red_flags) values
  (null, null, 'behavioral', 'junior',
   'Hãy giới thiệu ngắn gọn về bản thân và lý do bạn phù hợp với vị trí này.',
   ARRAY['Nêu kinh nghiệm, kỹ năng liên quan trực tiếp đến vị trí', 'Thành tích nổi bật có số liệu', 'Lý do phù hợp và mong muốn với công việc']::text[],
   ARRAY['Kể lan man đời tư', 'Không liên hệ với vị trí ứng tuyển']::text[]),
  (null, null, 'behavioral', 'mid',
   'Mục tiêu nghề nghiệp của bạn trong 2 đến 3 năm tới là gì?',
   ARRAY['Mục tiêu cụ thể, thực tế', 'Liên hệ với vị trí và công ty', 'Kế hoạch học hỏi để đạt mục tiêu']::text[],
   ARRAY['Mục tiêu mơ hồ', 'Không liên quan đến công việc']::text[]),
  (null, null, 'behavioral', 'mid',
   'Kể về một lần bạn mắc lỗi trong công việc và cách bạn khắc phục.',
   ARRAY['Thừa nhận lỗi cụ thể', 'Hành động khắc phục', 'Bài học và thay đổi sau đó']::text[],
   ARRAY['Không nhận lỗi', 'Đổ lỗi cho người khác']::text[])
on conflict do nothing;

-- Kiểm tra: tổng 141 câu
select i.name as nganh, count(*) as so_cau
from public.interview_questions q
left join public.industries i on i.id = q.industry_id
group by i.name order by i.name nulls first;

